# Generated by Django 4.1.7 on 2023-02-18 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_skill"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
